name: Build and test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [TestProject1, TestProject2, TestProject3]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
<<<<<<< HEAD
        run: dotnet test ${{ matrix.project }}/${{ matrix.project }}.csproj --no-build --verbosity normal
=======
        run: dotnet test ${{ matrix.project }}/${{ matrix.project }}.csproj --no-build --verbosity normal
>>>>>>> bb77fccaec107327d43b4d7b5a0c88a6b675a31d
